### ISSUE TITLE
Composer require invalid argument exception

### ISSUE THREAD

**Issue by arcostasi** [leprephp/di#1]
Hello Daniele, I working on a new micro framework for PHP and I would like to test your container with our micro framework, but it is giving error to use composer require according to the README steps.

[InvalidArgumentException]
Could not find a version of package lepre/di matching your minimum-stability (stable). 
Require it with an explicit version constraint allowing its desired stability.

**Comment by omoikane** [comment]
Because this project is in development stage, and we don't have a stable release yet.

Can you add "minimum-stability": "dev" in your composer.json?

More info here: https://getcomposer.org/doc/04-schema.md#minimum-stability

**Comment by arcostasi** [comment]
Ok, no problem! I put "minimum-stability": "dev" in my composer.json

thank you

**Comment by omoikane** [comment]
You are welcome ;)
